CREATE TABLE MEMBER (
  MEMBER_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  MEMBER_NAME NVARCHAR(255) collate Indic_General_100_BIN not null,
  SOCIETY_ID INT NOT NULL 
);

CREATE TABLE LOGIN (
 USER_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 USER_NAME NVARCHAR(255) collate Indic_General_100_BIN not null,
 PASSWORD INT,
 USER_ROLE INT,
 CREATER_ID INT,
 CREATE_DATE DATE,
 STATUS INT
);